config_generation:
  conversation_starter_frequency: 2

  automation:
    idle_cycle:
      procrastination_chance:
        min: -1
        max: -1
    behaviours:
      procrastination:
        duration_min: 60
        duration_max: 80
        preference:
          youtube: 1
          kittens: 1
