config_generation:
  conversation_starter_frequency: 2

  user_behaviour:
    procrastination_chance:
      min: -1
      max: -1
    procrastination_duration:
      min: 60
      max: 80
    procrastination_preference:
      youtube: 1
      kittens: 1
